export const GET_PROJECTS = 'GET_PROJECTS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const UPDATE_PROJECTS = 'UPDATE_PROJECTS';
export const DELETE_PROJECTS = 'DELETE_PROJECTS';
export const LOADING = 'LOADING';
